import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { LanguageProvider } from '@/lib/LanguageContext';
import "./globals.css";
import 'leaflet/dist/leaflet.css';

// Poppins shriftini ulash
const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // kerakli vaznlar
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "SinoLife",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uz" suppressHydrationWarning={true}>
      <body className={`${poppins.variable} font-sans antialiased`}>
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
