import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import { LanguageProvider } from '@/lib/LanguageContext';
import "./globals.css";
import 'leaflet/dist/leaflet.css';

// Poppins shriftini latin + cyrillic bilan ulash
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'latin-ext'], // faqat mavjud subsetlar
  display: 'swap',
  variable: '--font-poppins',
});

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
  display: 'swap',
  variable: '--font-roboto',
});
export const metadata: Metadata = {
  title: "SinoLife",
  description: "Generated by Readdy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uz" suppressHydrationWarning={true}>
      <body className={`${poppins.variable} ${roboto.variable}`} style={{ fontFamily: 'var(--font-poppins), var(--font-roboto), sans-serif' }}>
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
